Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Politiq.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

        // GET: /Welcome
        [Authorize]
        public ActionResult Welcome()
        {
            return View();
        }

        public string Regex()
        {
            int yeas = (int)decimal.Truncate(((10 / 13) * 58));
            return yeas.ToString();
        }
    }
}

Controllers/ParliamentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Politiq.Models.ObjectModel;
using Politiq.Models;

namespace Politiq.Controllers
{
    public class ParliamentController : Controller
    {
        private DAL db = new DAL();

        //
        // GET: /Parliament/

        [HttpPost]
        public int Open()
        {
            var lastSession = db.CommonsSessions.OrderByDescending(p => p.Ending).FirstOrDefault();

            if (lastSession != null && lastSession.Ending > DateTime.Now)
            {
                return 1;
            }

            var newSession = new CommonsSession
                {
                    Opening = DateTime.Now,
                    Ending = DateTime.Now.AddYears(5),
                    Dissolved = false
                };
            
            if(lastSession == null)
            {
                newSession.Legislature = 41;
                newSession.Session = 1; 
            }
            else
            {
                if (lastSession.Dissolved == true)
                {
                    newSession.Legislature = lastSession.Legislature + 1;
                    newSession.Session = 1;
                }
                else
                {
                    newSession.Legislature = lastSession.Legislature;
                    newSession.Session = lastSession.Session + 1;
                }
            }

            db.CommonsSessions.Add(newSession);
            db.SaveChanges();

            return 0;
        }

        [HttpPost]
        public int Prorogue()
        {
            var lastSession = db.CommonsSessions.OrderByDescending(p => p.Ending).FirstOrDefault();

            if (lastSession.Ending < DateTime.Now)
            {
                return 1;
            }
            else
            {
                lastSession.Ending = DateTime.Now;
                db.SaveChanges();
                return 0;
            }
        }

        [HttpPost]
        public int Dissolve()
        {
            var lastSession = db.CommonsSessions.OrderByDescending(p => p.Ending).FirstOrDefault();

            if (lastSession.Dissolved == true)
            {
                return 0;
            }
            else
            {
                lastSession.Ending = DateTime.Now;
                lastSession.Dissolved = true;
                db.SaveChanges();
                return 1;
            }
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Welcome";
}

<h2>Welcome</h2>
@if (User.Identity.IsAuthenticated)
{
    <p>@Html.ActionLink("Click here to log out", "Logout", "Account")</p>
}
else
{ 
    <p>@Html.ActionLink("Click here to log in", "Login", "Account")</p>
    <p>@Html.ActionLink("Click here to sign-up", "Register", "Account")</p>
}

Views/Home/Welcome.cshtml
@{
    ViewBag.Title = "Welcome";
}

<h2>Hi, <b>@Context.User.Identity.Name</b>! Welcome to my website!</h2>

<p>@Html.ActionLink("Log out", "Logout", "Account")</p>



<p>@Ajax.ActionLink("Open Parliament", "Open", "Parliament",
                     new AjaxOptions
                     {
                         HttpMethod = "Post",
                         Confirm = "Open a new session of Parliament?"
                     }
                     )</p>

<p>@Ajax.ActionLink("Prorogue Parliament", "Prorogue", "Parliament",
                    new AjaxOptions
                    {
                        HttpMethod = "Post",
                        Confirm = "Prorogue the current session of Parliament?"
                    }
                    )</p>

<p>@Ajax.ActionLink("Dissolve Parliament", "Dissolve", "Parliament",
                    new AjaxOptions
                    {
                        HttpMethod = "Post",
                        Confirm = "Dissolve Parliament and hold an election?"
                    }
                    )</p>